### ISSUE TITLE
Unexpected error: "Connection reset by peer"

### ISSUE THREAD

**Issue by aaronsteers** [singer-io/tap-pardot#4]
I am just setting up the Pardot API - mostly with success but I've run into the error below. Any ideas?

```
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

Full log output:
```
INFO https://pi.pardot.com/api/prospect/version/4/do/query - Making request to GET endpoint https://pi.pardot.com/api/prospect/version/4/do/query, with params {'format': 'json', 'output': 'bulk', 'updated_after': '2020-03-02 10:43:27', 'sort_by': 'updated_at', 'sort_order': 'ascending'}
CRITICAL ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Traceback (most recent call last):
  File "/venv/tap-pardot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/venv/tap-pardot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/venv/tap-pardot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/venv/tap-pardot/lib/python3.8/site-packages/urllib3/connection.py", line 352, in connect
    self.sock = ssl_wrap_socket(
  File "/venv/tap-pardot/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/venv/tap-pardot/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/venv/tap-pardot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/venv/tap-pardot/lib/python3.8/site-packages/urllib3/util/retry.py", line 400, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/venv/tap-pardot/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/venv/tap-pardot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/venv/tap-pardot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/venv/tap-pardot/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/venv/tap-pardot/lib/python3.8/site-packages/urllib3/connection.py", line 352, in connect
    self.sock = ssl_wrap_socket(
  File "/venv/tap-pardot/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/venv/tap-pardot/tap-pardot", line 11, in <module>
    load_entry_point('tap-pardot==0.2.0', 'console_scripts', 'tap-pardot')()
  File "/venv/tap-pardot/lib/python3.8/site-packages/singer/utils.py", line 229, in wrapped
    return fnc(*args, **kwargs)
  File "/venv/tap-pardot/lib/python3.8/site-packages/tap_pardot/__init__.py", line 37, in main
    sync(client, args.config, args.state, catalog)
  File "/venv/tap-pardot/lib/python3.8/site-packages/tap_pardot/sync.py", line 30, in sync
    for rec in stream_object.sync():
  File "/venv/tap-pardot/lib/python3.8/site-packages/tap_pardot/streams.py", line 93, in sync
    for rec in self.sync_page():
  File "/venv/tap-pardot/lib/python3.8/site-packages/tap_pardot/streams.py", line 79, in sync_page
    for rec in self.get_records():
  File "/venv/tap-pardot/lib/python3.8/site-packages/tap_pardot/streams.py", line 55, in get_records
    data = self.client.get(self.endpoint, **self.get_params())
  File "/venv/tap-pardot/lib/python3.8/site-packages/tap_pardot/client.py", line 150, in get
    return self._fetch("get", endpoint, format_params, **kwargs)
  File "/venv/tap-pardot/lib/python3.8/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/venv/tap-pardot/lib/python3.8/site-packages/tap_pardot/client.py", line 143, in _fetch
    content = self._make_request(method, url, params)
  File "/venv/tap-pardot/lib/python3.8/site-packages/tap_pardot/client.py", line 88, in _make_request
    response = requests.request(
  File "/venv/tap-pardot/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/venv/tap-pardot/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/venv/tap-pardot/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/venv/tap-pardot/lib/python3.8/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by dmosorast** [comment]
@aaronsteers That's a general "connection snapped" kind of error, and it could be one of a number of networking-related issues. It looks like it's trying to request a page, so if that's taking a long time to download, it gives more opportunity for the connection to snap on either Pardot's end, your machine's end, or somewhere in between.

Is it happening every time you try to run it? Is it a specific stream? Are you running it on a machine with a reliable network (e.g., wired in)?

**Comment by aaronsteers** [comment]
@dmosorast - It's running from ECS and this happens after about `31 minutes` of execution, on the 4th table or so (VisitorActivities). I don't think it is directly related to network _stability_, since ECS instance would have a very fast internet connection. It is possible there's some type of timeout that occurs after 30 minutes or so?

The same actually ran smoothly this morning, finishing all tables in 21 minutes. I'll keep an eye on this and post back if I have more info. Even if an interim connection failure, I wonder if it would be possible to configure retries for events such as these? Happy to help contribute code here if something like that would make sense.

**Comment by dmosorast** [comment]
I'm not familiar with ECS configuration, but since it's multi-tenant there could be some kind of timeout on long lived connections in the surrounding infrastructure that snap them. It would certainly be good to have a retry pattern around these kinds of exceptions.

If you can get a solid reproduction down and can submit a PR, that would be great!

**Comment by aaronsteers** [comment]
Closing this stale issue, as is has not been recurring for us. As suggested, this may have been a network-related issue.
